### ISSUE TITLE
Very Important Talk

### ISSUE THREAD

**Issue by jMuzsik** [brooklynjs/brooklynjs.github.io#520]
## BrooklynJS Talk Submission

**Talk Title:**
JS in relation to life

**Talk Description:**
The basis is this: a satire related to modern day JS. I will predominantly relate modern day problems/politics with the ecosystem of JS. The focus will be on encapsulating how the community of JS and code can be a catalyst for global change in the politics/problems of society in general but in a subtle way.

**Name**:
Jerry Muzsik

**Preferred Pronouns**:
He/Him

**Twitter Handle (optional)**:

**Website (optional):**
Check out some of my past medium posts to get a feel for my voice:
https://medium.com/@muzsik33

**Months Available to Speak:** We recommend selecting multiple months (up to 3) that you are available to speak. We'll keep your PR open throughout those months if you aren't accepted the first time!
November (I will be in South America December and many months afterward) - I have been in NYC for a while, been to Brooklyn JS the past 6 or so months straight

**Comment by paladique** [comment]
@jMuzsik Thank you for your submission! Your talk was not included in this month's lineup, but you get firsties on tickets! Email organizers@brooklynjs.com for details.

Since your only availability was for November, we will close this for now. You're welcome to resubmit your proposal when you're anticipating being back in town.
